directories:
  logging: ../conf/log
  rules: rules
  lib: lib
  param: parameters
  config: config

location:
  latitude: 52.5185537
  longitude: 13.3758636
  elevation: 43

mqtt:
  connection:
    client_id: HABApp
    host: localhost
    password: ''
    port: 1883
    tls: false
    tls_insecure: false
    user: ''
    tls_ca_cert_path: ''  # Path to the CA certificate files that are to be treated as trusted
  publish:
    qos: 0
    retain: false
  subscribe:
    qos: 0
    topics:
    - '#'
    - 0
  general:
    listen_only: false

openhab:
  connection:
    host: localhost
    port: 8080
    user: ''
    password: ''
  general:
    listen_only: false
    wait_for_openhab: true
  ping:
    enabled: true
    interval: 10
    item: Ping
