language: python
os: linux

jobs:
  include:
    - &python_38
      python: 3.8
      script: tox
      install: pip install tox
      env: TOXENV=py38

    - <<: *python_38
      python: 3.6
      env: TOXENV=py36

    - <<: *python_38
      python: 3.7
      env: TOXENV=py37

    - <<: *python_38
      python: 3.9
      env: TOXENV=py39

    - <<: *python_38
      env: TOXENV=flake

    - <<: *python_38
      python: 3.8
      env: TOXENV=docs

    - language: shell
      install:
        # test docker build
        - docker build -t habapp .
        - docker run -d --name habapp habapp
      script:
        # Allow the container to start properly
        - sleep 5
        # output stdout to travis in case we can not start the container
        - docker logs habapp
        # test if container is still running
        # -q means quiet and will return 0 if a match is found
        - docker ps | grep -q habapp
        # Show logs from HABApp
        - docker exec habapp tail -n +1 /config/log/HABApp.log
